module.exports = {
    // Menu and Info Box
    home: "Home",
    note: "Notes",
    books: "Books",
    reading: "Reading",
    about: "About",
    friends: "Friends",
    contact: "Contact",    
    resume: "Resume",
    build_with: "Build with:",
    list_of_posts: "List Of Posts",
    expand_the_list: "Expand the list",
    expand_the_box: "Expand the box",
    remove_filtering: "Remove filtering",
    active_category_filter: "Active Category Filter:",
    // Info Bar
    more: "More",
    // Action bar
    back_to_home: "Back to home",
    search: "Search",
    filter: "Category Filter",
    all_posts: "All Posts",
    font_size: "Font size",
    fullscreen: "Fullscreen",
    theme: "Theme",
    scroll_to_top: "Scroll to top",
    // Search
    search_by: "Search by",
    search: "Search",
    // Contact
    email_to_me: "You can contact me via email: ",
    contact_desc: "You can also contact me via my Telegram (https://t.me/zuolan), or contact me directly using the form below:",
    send: "Send",
    network_error: "Network error",
    field_required: "Field required",
    contact_name: "Your Name",
    contact_mail: "Your Email",
    mail_not_valid: "Mail not valid",
    contact_message: "Message",
    // Post
    tableOfContents: "Table Of Contents",
    published_before: "Published ",
    published_after: " days ago",
    published_today: "Published Today",
    published_yesterday: "Published Yesterday",
    published_three_days: "Published 3 days ago",
    over_date: "This post has been over 100 days since the date of publication.",
    share_before: "Share",
    share_after: "to",
}