module.exports = {
    // Menu and Info Box
    home: "首页",
    note: "笔记",
    books: "书架",
    reading: "在读",
    about: "关于",
    friends: "邻居",
    contact: "向我提问",    
    resume: "简历",
    build_with: "网站基于以下技术构建：",
    list_of_posts: "文章列表",
    expand_the_list: "展开列表",
    expand_the_box: "关闭列表",
    remove_filtering: "清除过滤",
    active_category_filter: "当前分类列表：",
    // Info Bar
    more: "更多",
    // Action bar
    back_to_home: "返回首页",
    search: "搜索",
    filter: "分类",
    all_posts: "所有文章",
    font_size: "字体大小",
    fullscreen: "全屏",
    theme: "主题",
    scroll_to_top: "返回顶部",
    // Search
    search_by: "搜索基于",
    search: "搜索",
    // Contact
    email_to_me: "您可以通过电子邮件联系我（即时收到）：",
    contact_desc: "您也可以通过我的 Telegram（https://t.me/zuolan）账号联系到我，或者直接使用下面表单与我联系（信息将发送到我的邮箱）：",
    send: "发送",
    network_error: "网络错误",
    field_required: "此输入框必填",
    contact_name: "您的称呼",
    contact_mail: "您的邮箱（我的回复将发送到您的邮箱中）",
    mail_not_valid: "邮件格式无效",
    contact_message: "您想对我说什么",
    // Post
    tableOfContents: "目录",
    published_before: "文本于",
    published_after: "天前发布",
    published_today: "本文于今天发布",
    published_yesterday: "本文于昨天发布",
    published_three_days: "本文于前天发布",
    over_date: "本文自发布日起已经超过100天，文章信息可能已经过时，请酌情阅读。",
    share_before: "分享",
    share_after: "到其他地方",
}